<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RestoranSeeder extends Seeder
{
    public function run()
    {
        DB::table('restoran')->insert([
            [
                'nama_restoran'       => 'Kampoeng Noodle',
                'alamat'              => 'Ruko The Opera 3, Jl. Patih No.6 Blok B4, Tlk. Tering, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29444',
                'kota'                => 'Batam',
                'provinsi'            => 'Kepulauan Riau',
                'kecamatan_kelurahan' => 'Batam Kota',
                'deskripsi'           => 'Kampoeng Noodle merupakan kedai mie yang menyediakan berbagai macam olahan mie dengan bumbu khas.',
                'jam_operasional'     => '06.00-22.00',
                'status_halal'        => 'certified',
                'latitude'            => 1.143378,
                'longitude'           => 104.05873,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'nama_restoran'       => 'Donburo',
                'alamat'              => 'Greenland Batam Centre Ruko Greenland Blok B No.3A, Kota Batam, Kepulauan Riau 29464',
                'kota'                => 'Batam',
                'provinsi'            => 'Kepulauan Riau',
                'kecamatan_kelurahan' => 'Batam Kota',
                'deskripsi'           => 'Donburo merupakan restoran yang menyediakan makanan khas Jepang.',
                'jam_operasional'     => '09.00-22.00',
                'status_halal'        => 'certified',
                'latitude'            => 1.138144,
                'longitude'           => 104.063569,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'nama_restoran'       => 'Holy Meat and Grill',
                'alamat'              => 'Jl. Raja M Tahir No.11, Tlk. Tering, Batam Center, Kota Batam, Kepulauan Riau 29444',
                'kota'                => 'Batam',
                'provinsi'            => 'Kepulauan Riau',
                'kecamatan_kelurahan' => 'Batam Kota',
                'deskripsi'           => 'Holy Meat and Grill merupakan resto yang menyediakan makanan spesialis daging panggang.',
                'jam_operasional'     => '10.00-22.00',
                'status_halal'        => 'certified',
                'latitude'            => 1.138525,
                'longitude'           => 104.063914,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'nama_restoran'       => 'Ikan Bakar Cianjur',
                'alamat'              => 'Jl. Centre Point, Tlk. Tering, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29444',
                'kota'                => 'Batam',
                'provinsi'            => 'Kepulauan Riau',
                'kecamatan_kelurahan' => 'Batam Kota',
                'deskripsi'           => 'Ikan Bakar Cianjur merupakan resto yang menyediakan makanan dengan berbagai macam menu khas nusantara.',
                'jam_operasional'     => '10.00-22.30',
                'status_halal'        => 'certified',
                'latitude'            => 1.140676,
                'longitude'           => 104.067741,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'nama_restoran'       => 'Warung Taburai',
                'alamat'              => 'Komp. Mahkota Raya, Ruko Blk. F No.8-9, Tlk. Tering, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29444',
                'kota'                => 'Batam',
                'provinsi'            => 'Kepulauan Riau',
                'kecamatan_kelurahan' => 'Batam Kota',
                'deskripsi'           => 'Warung Taburai merupakan Rumah Makan yang menyediakan makanan khas nusantara khususnya Sumatera Barat.',
                'jam_operasional'     => '24 Jam',
                'status_halal'        => 'certified',
                'latitude'            => 1.144766,
                'longitude'           => 104.056469,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'nama_restoran'       => 'Maru Bake House',
                'alamat'              => 'Komp. Superblock, Sydney Hotel No.6, Sungai Panas, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29444',
                'kota'                => 'Batam',
                'provinsi'            => 'Kepulauan Riau',
                'kecamatan_kelurahan' => 'Batam Kota',
                'deskripsi'           => 'Maru Bake House merupakan toko roti yang menyediakan berbagai macam jenis roti halal.',
                'jam_operasional'     => '11.30-22.00',
                'status_halal'        => 'certified',
                'latitude'            => 1.140694,
                'longitude'           => 104.049368,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'nama_restoran'       => 'Mie Tarempa',
                'alamat'              => 'Ruko Royal Sincom, Blk. D No.15-16, Tlk. Tering, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29431',
                'kota'                => 'Batam',
                'provinsi'            => 'Kepulauan Riau',
                'kecamatan_kelurahan' => 'Batam Kota',
                'deskripsi'           => 'Mie Tarempa merupakan restoran yang menyediakan aneka makanan khas Kepulauan Riau.',
                'jam_operasional'     => '06.00-21.00',
                'status_halal'        => 'certified',
                'latitude'            => 1.128108,
                'longitude'           => 104.069769,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'nama_restoran'       => 'Bebek Carok',
                'alamat'              => 'Komplek Ruko Air Mas Blok A2 No.2, Tlk. Tering, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29444',
                'kota'                => 'Batam',
                'provinsi'            => 'Kepulauan Riau',
                'kecamatan_kelurahan' => 'Batam Kota',
                'deskripsi'           => 'Bebek Carok merupakan restoran yang menyediakan makanan khas nusantara yang berasal dari Madura.',
                'jam_operasional'     => '24 Jam',
                'status_halal'        => 'certified',
                'latitude'            => 1.136721,
                'longitude'           => 104.064948,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'nama_restoran'       => 'Marugame',
                'alamat'              => 'Komplek Fanindo, Jl. Ahmad Yani Sanctuary Garden No.02H, Tlk. Tering, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29444',
                'kota'                => 'Batam',
                'provinsi'            => 'Kepulauan Riau',
                'kecamatan_kelurahan' => 'Batam Kota',
                'deskripsi'           => 'Marugame merupakan restoran yang menyediakan makanan khas mie Jepang dengan berbagai macam menu pilihan.',
                'jam_operasional'     => '10.00-22.00',
                'status_halal'        => 'certified',
                'latitude'            => 1.133881,
                'longitude'           => 104.065048,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'nama_restoran'       => 'KFC Fanindo',
                'alamat'              => 'Jl. Ahmad Yani, Tlk. Tering, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29444',
                'kota'                => 'Batam',
                'provinsi'            => 'Kepulauan Riau',
                'kecamatan_kelurahan' => 'Batam Kota',
                'deskripsi'           => 'KFC merupakan restoran cepat saji yang menyediakan berbagai olahan ayam goreng dan menu lainnya.',
                'jam_operasional'     => '24 Jam',
                'status_halal'        => 'none',
                'latitude'            => 1.134147,
                'longitude'           => 104.06545,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'nama_restoran'       => 'Burger King',
                'alamat'              => 'Jl. Ahmad Yani, Tlk. Tering, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29444',
                'kota'                => 'Batam',
                'provinsi'            => 'Kepulauan Riau',
                'kecamatan_kelurahan' => 'Batam Kota',
                'deskripsi'           => 'Burger King merupakan restoran cepat saji yang menyediakan berbagai olahan burger dan menu lainnya.',
                'jam_operasional'     => '24 Jam',
                'status_halal'        => 'certified',
                'latitude'            => 1.13435,
                'longitude'           => 104.066046,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'nama_restoran'       => 'Mako',
                'alamat'              => 'Jl. Ahmad Yani, Tlk. Tering, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29444',
                'kota'                => 'Batam',
                'provinsi'            => 'Kepulauan Riau',
                'kecamatan_kelurahan' => 'Batam Kota',
                'deskripsi'           => 'Mako merupakan toko kue dan roti yang menjual berbagai macam kue dan roti seperti lapis legit, kue kering, dan lainnya.',
                'jam_operasional'     => '09.00-22.00',
                'status_halal'        => 'certified',
                'latitude'            => 1.134222,
                'longitude'           => 104.065564,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'nama_restoran'       => 'Kebuli Saudi',
                'alamat'              => 'Jl. Ruko Greenland, Tlk. Tering, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29444',
                'kota'                => 'Batam',
                'provinsi'            => 'Kepulauan Riau',
                'kecamatan_kelurahan' => 'Batam Kota',
                'deskripsi'           => 'Kebuli Saudi merupakan restoran khas Timur Tengah yang menjual nasi kebuli beserta aneka olahan ayam.',
                'jam_operasional'     => '10.30-21.00',
                'status_halal'        => 'self_claimed',
                'latitude'            => 1.137948,
                'longitude'           => 104.065967,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'nama_restoran'       => 'Morning Bakery',
                'alamat'              => 'Tlk. Tering, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29444',
                'kota'                => 'Batam',
                'provinsi'            => 'Kepulauan Riau',
                'kecamatan_kelurahan' => 'Batam Kota',
                'deskripsi'           => 'Morning Bakery merupakan restoran yang menyediakan aneka makanan dan minuman untuk sarapan dan makan siang.',
                'jam_operasional'     => '06.00-21.00',
                'status_halal'        => 'certified',
                'latitude'            => 1.137347,
                'longitude'           => 104.064804,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'nama_restoran'       => 'Ayam Gepuk Pak Gembus',
                'alamat'              => 'Ruko Air Mas A2/7, Jl. Ruko Greenland, Tlk. Tering, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29444',
                'kota'                => 'Batam',
                'provinsi'            => 'Kepulauan Riau',
                'kecamatan_kelurahan' => 'Batam Kota',
                'deskripsi'           => 'Ayam Gepuk Pak Gembus menyediakan berbagai aneka ayam goreng dengan sambal pedas yang khas.',
                'jam_operasional'     => '10.00-22.00',
                'status_halal'        => 'certified',
                'latitude'            => 1.136848,
                'longitude'           => 104.064828,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'nama_restoran'       => 'Warung Jowo Pacitan',
                'alamat'              => 'Komp. Air Mas, Jalan Mitra Raya, Tlk. Tering, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29444',
                'kota'                => 'Batam',
                'provinsi'            => 'Kepulauan Riau',
                'kecamatan_kelurahan' => 'Batam Kota',
                'deskripsi'           => 'Warung Jowo Pacitan menyediakan aneka makanan nasi dengan lauk berbagai macam khas masakan Jawa.',
                'jam_operasional'     => '07.00-22.00',
                'status_halal'        => 'self_claimed',
                'latitude'            => 1.136967,
                'longitude'           => 104.064695,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'nama_restoran'       => 'Mula Patisserie',
                'alamat'              => 'Jl. Ruko Greenland No.3A Blok C, Tlk. Tering, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29432',
                'kota'                => 'Batam',
                'provinsi'            => 'Kepulauan Riau',
                'kecamatan_kelurahan' => 'Batam Kota',
                'deskripsi'           => 'Mula Patisserie menyediakan aneka makanan dan minuman terkhusus berbagai macam dessert.',
                'jam_operasional'     => '11.30-22.00',
                'status_halal'        => 'certified',
                'latitude'            => 1.137817,
                'longitude'           => 104.064068,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'nama_restoran'       => 'Sambal Bakaran',
                'alamat'              => 'Ruko Mitra Junction, Jl. Dang Merdu No.28-29 Blok B2, Teluk Tering, Batam Kota, Kota Batam, Kepulauan Riau 29444',
                'kota'                => 'Batam',
                'provinsi'            => 'Kepulauan Riau',
                'kecamatan_kelurahan' => 'Batam Kota',
                'deskripsi'           => 'Sambal Bakaran menyediakan aneka hidangan ayam goreng dengan sambal khas.',
                'jam_operasional'     => '11.00-23.00',
                'status_halal'        => 'certified',
                'latitude'            => 1.138945,
                'longitude'           => 104.057938,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'nama_restoran'       => 'Daun Pisang Resto',
                'alamat'              => 'Ruko Mitra Hoki, Jl. Raja H. Fisabilillah No.6-9, Tlk. Tering, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29432',
                'kota'                => 'Batam',
                'provinsi'            => 'Kepulauan Riau',
                'kecamatan_kelurahan' => 'Batam Kota',
                'deskripsi'           => 'Daun Pisang Resto menyediakan aneka macam makanan berat seperti nasi maupun makanan ringan dan dessert.',
                'jam_operasional'     => '10.00-22.00',
                'status_halal'        => 'certified',
                'latitude'            => 1.139445,
                'longitude'           => 104.057462,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'nama_restoran'       => 'Se\'indonesia Sei Sapi',
                'alamat'              => 'Tlk. Tering, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29444',
                'kota'                => 'Batam',
                'provinsi'            => 'Kepulauan Riau',
                'kecamatan_kelurahan' => 'Batam Kota',
                'deskripsi'           => 'Se\'indonesia menyediakan makanan sei sapi dan ayam dengan cita rasa yang khas.',
                'jam_operasional'     => '24 Jam',
                'status_halal'        => 'certified',
                'latitude'            => 1.132318,
                'longitude'           => 104.059734,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'nama_restoran'       => 'Dondon',
                'alamat'              => 'Ruko Superblock Sydney Hotel No.4, Sungai Panas, Kota Batam, Kepulauan Riau 29444',
                'kota'                => 'Batam',
                'provinsi'            => 'Kepulauan Riau',
                'kecamatan_kelurahan' => 'Batam Kota',
                'deskripsi'           => 'Dondon merupakan restoran yang menyediakan aneka makanan khas Jepang.',
                'jam_operasional'     => '11.00-22.00',
                'status_halal'        => 'certified',
                'latitude'            => 1.140628,
                'longitude'           => 104.049261,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'nama_restoran'       => 'Rumah Makan Sunda Ibu Joko',
                'alamat'              => 'Tlk. Tering, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29444',
                'kota'                => 'Batam',
                'provinsi'            => 'Kepulauan Riau',
                'kecamatan_kelurahan' => 'Batam Kota',
                'deskripsi'           => 'Rumah Makan Sunda Ibu Joko menyediakan makanan dengan cita rasa khas Sunda.',
                'jam_operasional'     => '08.00-21.00',
                'status_halal'        => 'certified',
                'latitude'            => 1.148867,
                'longitude'           => 104.062527,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'nama_restoran'       => 'Gultik Pak Wongso',
                'alamat'              => 'Ruko Royal Sincom, Blk. A No.16-18, Tlk. Tering, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29444',
                'kota'                => 'Batam',
                'provinsi'            => 'Kepulauan Riau',
                'kecamatan_kelurahan' => 'Batam Kota',
                'deskripsi'           => 'Gultik Pak Wongso menyediakan aneka makanan seperti gultik, bakaran, dan lainnya.',
                'jam_operasional'     => '17.00-23.00',
                'status_halal'        => 'certified',
                'latitude'            => 1.129061,
                'longitude'           => 104.068606,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'nama_restoran'       => 'RM. Pondok Kriuk',
                'alamat'              => 'Komplek Ruko Air Mas Blok A2 No.4-5, Batam Centre, Tlk. Tering, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29461',
                'kota'                => 'Batam',
                'provinsi'            => 'Kepulauan Riau',
                'kecamatan_kelurahan' => 'Batam Kota',
                'deskripsi'           => 'RM. Pondok Kriuk menyediakan berbagai macam makanan khas nusantara.',
                'jam_operasional'     => '07.00-21.30',
                'status_halal'        => 'self_claimed',
                'latitude'            => 1.136805,
                'longitude'           => 104.064886,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'nama_restoran'       => 'Tjap Nyonya',
                'alamat'              => 'Belian, Kec. Batam Kota, Kota Batam, Kepulauan Riau',
                'kota'                => 'Batam',
                'provinsi'            => 'Kepulauan Riau',
                'kecamatan_kelurahan' => 'Batam Kota',
                'deskripsi'           => 'Tjap Nyonya menyediakan berbagai macam menu Ramen dengan citarasa yang khas.',
                'jam_operasional'     => '10.00-22.00',
                'status_halal'        => 'self_claimed',
                'latitude'            => 1.129502,
                'longitude'           => 104.07261,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'nama_restoran'       => 'Kedai Kopi & Roti Atok\'s',
                'alamat'              => 'Ruko Royal Sincom Blok F No.18-19, Batam Center, Tlk. Tering, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29444',
                'kota'                => 'Batam',
                'provinsi'            => 'Kepulauan Riau',
                'kecamatan_kelurahan' => 'Batam Kota',
                'deskripsi'           => 'Kedai Kopi Atok\'s menyediakan aneka macam makanan dan minuman khas nusantara.',
                'jam_operasional'     => '07.30-22.30',
                'status_halal'        => 'self_claimed',
                'latitude'            => 1.128774,
                'longitude'           => 104.071188,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'nama_restoran'       => 'Love Seafood Batam Centre',
                'alamat'              => 'Jl. Raja H. Fisabilillah No.12B, Tlk. Tering, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29444',
                'kota'                => 'Batam',
                'provinsi'            => 'Kepulauan Riau',
                'kecamatan_kelurahan' => 'Batam Kota',
                'deskripsi'           => 'Love Seafood menyediakan aneka macam olahan seafood segar.',
                'jam_operasional'     => '10.00-23.00',
                'status_halal'        => 'certified',
                'latitude'            => 1.14531,
                'longitude'           => 104.058613,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'nama_restoran'       => 'Saung Sunda Sawargi',
                'alamat'              => 'Jl. Raja H. Fisabilillah No.1, Tlk. Tering, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29444',
                'kota'                => 'Batam',
                'provinsi'            => 'Kepulauan Riau',
                'kecamatan_kelurahan' => 'Batam Kota',
                'deskripsi'           => 'Saung Sunda Sawargi menyediakan aneka macam makanan khas Sunda.',
                'jam_operasional'     => '10.00-21.00',
                'status_halal'        => 'self_claimed',
                'latitude'            => 1.140995,
                'longitude'           => 104.069108,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'nama_restoran'       => 'Martabak Pecenongan 78',
                'alamat'              => 'Jl. Raja M Tahir No.12, Tlk. Tering, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29444',
                'kota'                => 'Batam',
                'provinsi'            => 'Kepulauan Riau',
                'kecamatan_kelurahan' => 'Batam Kota',
                'deskripsi'           => 'Martabak Pecenongan 78 menyediakan berbagai macam martabak dengan topping yang melimpah.',
                'jam_operasional'     => '14.00-23.00',
                'status_halal'        => 'certified',
                'latitude'            => 1.136534,
                'longitude'           => 104.065397,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'nama_restoran'       => 'Warung Sego Sambel',
                'alamat'              => 'Tlk. Tering, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29444',
                'kota'                => 'Batam',
                'provinsi'            => 'Kepulauan Riau',
                'kecamatan_kelurahan' => 'Batam Kota',
                'deskripsi'           => 'Warung Sego Sambel menyediakan berbagai macam makanan dengan citarasa nusantara.',
                'jam_operasional'     => '08.00-21.00',
                'status_halal'        => 'self_claimed',
                'latitude'            => 1.137041,
                'longitude'           => 104.064541,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
        ]);
    }
}